### ISSUE TITLE
Auth/Register

### ISSUE THREAD

**Issue by SenRecep** [SenRecep/labby#4]
- [x] Kullanıcı kayıt isteğini yakalama
- [x] Kayıt edilmek istenen bilgilerin veritabanında unique olması gerekenlerin sorgulanması
    - [x] Kayıt bulunmamış ise kayıt işleminin tamamlanması
    - [x] Kayıt bulunmuş ise hata mesajının gösterilmesi

**Comment by hiikmetgezmen** [comment]
Auth/Register section completed
